spring:
    application:
        name: eureka-service
server:
    port: 8081
    error:
        include-message: always
        include-binding-errors: always

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8081/eureka
        register-with-eureka: false
        fetch-registry: false
    instance:
        prefer-ip-address: true